# Main configuration for species and data paths

species: "Human"
tax_id: 9606

ref_genome: "hg38"
anc_alleles: 
  path: "examples/data/Human/ancestral_alleles/homo_sapiens_ancestor_GRCh38"
  prefix: "homo_sapiens_ancestor_chr"

genome_annotation: "examples/data/Human/annotation/Human.gtf.gz"
gene2go: "examples/data/Human/annotation/gene2go.gz"

# Quality control filters
# Hardy-Weinberg equilibrium p-value threshold for balancing selection
hwe_pvalue: 0.001

# Repeat filters
rmsk: "examples/data/Human/repeats/hg38.rmsk.autosomes.bed" # repeat masker
seg_dup: "examples/data/Human/repeats/hg38.seg.dups.autosomes.bed" # segment duplications
sim_rep: "examples/data/Human/repeats/hg38.simple.repeats.autosomes.bed" # simple repeats

ploidy: 2

# Population definitions
populations:
  - YRI
  - CHS

# Data file configuration
# Base folder for resources
data_folder: "examples/data/Human/raw"
  
# VCF file naming convention: {file_prefix}chr{chr_name}{file_suffix}
vcf_prefix: "full_chr"
vcf_suffix: ".vcf.gz"
    
# Sample metadata file
metadata: "examples/data/Human/metadata/example_metadata.txt"
  
# Chromosome range to analyze
chromosomes:
  #- 1
  #- 2
  #- 3
  #- 4
  #- 5
  #- 6
  #- 7
  #- 8
  #- 9
  #- 10
  #- 11
  #- 12
  #- 13
  #- 14
  #- 15
  #- 16
  #- 17
  #- 18
  #- 19
  - 20
  - 21
  #- 22
  #- X    
  #- Y 

selscan_config: "config/selscan.yaml"
betascan_config: "config/betascan.yaml"
dadi_config: "config/dadi-cli.yaml"
scikit_allel_config: "config/scikit-allel.yaml"
